### ISSUE TITLE
18 odd entries 

### ISSUE THREAD

**Issue by drdhaval2785** [sanskrit-lexicon/LRV#1]
Every entry in LRV starts with `$--` markup.
The following 18 entries do not have that markup.
They start with `$//` mostly.

@Andhrabharati , is there any reason why they are so, or some typo / algo error?

```
काश् $//With निस्-, 1. to open; 2. to take out, to present to the sight; 3. to turn oat, to banish, e.g. गृहान्निष्काशयेत्.//With प्र-, 1. to show, to discover, to disclose, to reveal, अवसरोऽयमानात्मानं प्रकाशयितुम् /Sak./i.; 2. to lighten, to illumine, यथा प्रकाशयत्येकः कृत्स्नं लोकमिमं रविः /Bg./xiii.33; 3. to bring to light, to make public, to communicate, to proclaim, कदाचित्कुपितं मित्रं सर्वदोषं प्रकाशयेत् <i>Chāṇakya</i>.
कॢप् $//With आ-, to adorn, to decorate.//With प्र-, 1. to prepare, to make ready; 2. to scheme, to sketch.//With परि-, 1. to prepare; 2. to decide, to determine.//With वि-, to doubt.//With सम्-, 1. to intend; 2. to resolve, to determine on.//With समुप-, to prepare.
तुद् $//With प्र-, to press, to request repeatedly, प्रविश गृहमिति प्रतोद्यमाना न चलति भाग्यकृतां दशां विलोक्य /Mrich./i.
धुक्ष् $//With सम्-, to kindle, to excite, निर्वाणभूयिष्ठमथास्य वीर्यं संधुक्षयंतीव वपुर्गुणेन /K.S./iii.52.
पठ् $//With परि-, to teach.
पद् $//With आ-, 1. to bring to the state of, to lead to, to reduce to, /R./v.5; 2. to bring to subjection; 3. to bring on, to produce, to cause.//With उद्-, 1. to produce, to create; 2. to beget.//With उप-, 1. to lead to; 2. to offer, to present, /R./xv.18, xvi.32; 3. to accomplish, to achieve, दैवकार्यमुपपादयिष्यतः /R./xi.91; 4. to justify, to make conformable to, to give reasons for.//With निस्-, 1. to produce, to manufacture, to prepare, e.g. त्वं तावदेकं पट्टं नित्यमेव निष्पादयसि.//With प्रति-, 1. to give, to present, to bestow on, /M./xi.4; 2. to substantiate by proof, to establish, to prove, e.g. तदेव प्रतिपादयति; 3. to consider, to regard as, to declare to be.//With व्या-, to kill.//With सम्-, 1. to accomplish, to bring about, to effect, संपाद्य पाणिग्रहणं स राजा /R./vii.29; 2. to make ready, to prepare, to manufacture; 3. to obtain, to attain, to acquire; 4. to strike a bargain.
पृ $//With व्या-, 1. to cause to work, to engage in, व्यापारयामास करं किरीटे /R./vi.19, or व्यापारयामास विलोचनानि /K.S./iii.67; 2. to appoint, व्यापारितः शूलभृता विधाय सिंहत्वमंकागतसत्ववृत्ति /R./ii.38.
प्यै $//With आ-, 1. to make comfortable; 2. to enlarge.
यम् $//With नि-, to control, to check, to regulate, नियमयसि विमार्गप्रस्थिताना तदंडः /Sak./v.
यस् $//With आ-, to torment, to trouble.
राज् $//With निस्-, 1. to adorn, to make brilliant, to illuminate; 2. to wave lights before an idol or a king (as an act of worship), नीराजयंति भूपालाः पादपाठान्तभुतलम् /Pr.Ch./ii.
राध् $//With आ-, 1. to propitiate, to please, to conciliate, न तु प्रतिनिविष्टमूर्खजनचित्तमाराधयेत् /Bhartr./ii.4; 2. to serve, to worship, आराध्यैनं शरवणभवं देवमुल्लंघिताध्वा /Megh./i.45.
विश् $//With नि-, 1. to apply, to bend (the mind); 2. to draw, to portray, e.g. चित्रे निवेश्य परिकल्पितसत्वयोगा रूपोच्चयेन मनसा विधिना कृता नु; 3. to put, to place; 4. to enter on, to commit.//With प्र-, to usher.//With विनि-, to put, to fix, /K.S./i.49.
शिष् $//With वि-, to excel, to surpass.
शी $//With अति-, to cause to excel, (यः) धाम्नातिशाययति धाम सहस्रधाम्नः /Mud./iii.
श्रम् $//With वि-, 1. to take rest, to repose; 2. to cause to alight.
श्वस् $//With आ-, to console, to comfort.//With वि-, to inspire confidence, to cause to confide.//With समा-, to encourage, to cheer up.
स्कंभ् $//With वि-, to impede, to obstruct.
```

**Comment by Andhrabharati** [comment]
Pl. see my mail 2 hrs back.
I thought you would be preparing the file locally first and then (finally) upload to Github.

Yes, these were deliberately marked thus.
I had used // mark wherever I felt a new para is to be there (for display) in the text.

`-----------------------`
Here is the mail content, for the benefit of others (if they happen to come here)--

> I am sure you'd be looking 'inside' the data in my file once, to know the way it was 'made'-- say (a) the // mark for a para-break, (b)  /.../ for `<ls>` names, (c) using xxx at the gender/lex column etc.
> 
> Also the HWs with braced letter(s) are to be 'treated' to form althws; and of course, the comma separated group entries are to be separated out into individual entries.

**Comment by Andhrabharati** [comment]
These entries do not have their own body part, but only with the upasarga some body portion is given.
And all upasargas start on a new line/para (//With zzz).

**Comment by Andhrabharati** [comment]
And pl. note that my notation is not page-column, but is page-seq no. (within the page)

How to accommodate this in the CDSL `<pc>` format?

The simplest way is to leave the 'seq no.' and forget about adding the 'column' in the data.

**Comment by Andhrabharati** [comment]
My `<p>` is the notation for 'parent' entry and `<b>` is for child ('baby') entry, i.e. the comp. word

**Comment by drdhaval2785** [comment]
Yes. I am uploading the file to Github and uploading the sequential changes which are being made.
This is just for keeping track of changes and see visually the changes made at every step.
This is not for public display. 
Once the data is fine in this repository LRV, we will move it to more public csl-orig repository and update the scripts to regenerate all the details for LRV dictionary to display on Cologne server.
I am looking into the text data and using the various markups you used to extract the relevant information.

**Comment by drdhaval2785** [comment]
> These entries do not have their own body part, but only with the upasarga some body portion is given.

This does not seem to be true for all above entries.
![Screenshot_2022-09-20_22-34-10](https://user-images.githubusercontent.com/5755132/191320547-e7857b2a-0014-4f5e-af40-ecda582bb3b9.png)

**Comment by drdhaval2785** [comment]
> These entries do not have their own body part, but only with the upasarga some body portion is given.

OK
