### ISSUE TITLE
Add to csl-orig repository

### ISSUE THREAD

**Issue by drdhaval2785** [sanskrit-lexicon/LRV#15]
Majority of headword errors which could be caught by program have been handled.
Time to merge the data in the csl-orig repository and make it part of CDSL workflow.

**Comment by drdhaval2785** [comment]
LRV has been added to csl-orig repository and some tweakings have been made in csl-pywork and csl-websanlexicon repository to allow generation of LRV for local host.
Works well on my localhost.

Image files are not uploaded yet.
Line breaks before new meaning is not inserted yet.

Otherwise looks good to me.

@funderburkjim, kindly check whether you can make it work on localhost?

**Comment by gasyoun** [comment]
> Majority of headword errors which could be caught by program have been handled.

Thanks

**Comment by drdhaval2785** [comment]
Alternate headwords (parsed from brackets) are now added in csl-orig repository.

**Comment by drdhaval2785** [comment]
Feminine forms are also added to csl-orig repository.
This placeholder may be treated to be over.

**Comment by funderburkjim** [comment]
##  local installation works

* Pulled repositories csl-pywork, csl-websanlexicon, csl-apidev, and of course csl-orig.
* in csl-pywork/v02: `sh generate_dict.sh lrv  ../../lrv`
   * no problems noticed
   * sh xmlchk_xampp.sh lrv
      * python3 ../../xmlvalidate.py ../../lrv/pywork/lrv.xml ../../lrv/pywork/lrv.dtd
      * ok   xml fine

**Comment by funderburkjim** [comment]
## basic display works
![image](https://user-images.githubusercontent.com/6393033/195647310-d5339ef8-afb3-4972-a203-c82e5e78b1e9.png)

**Comment by funderburkjim** [comment]
## simple-search dict problem
![image](https://user-images.githubusercontent.com/6393033/195648854-5763b2cd-fee7-4218-b199-693a0f7b3f4b.png)
The menu for dictionaries doesn't have lrv yet (that's why with partial name 'lr', no dictionary shown.

**Comment by funderburkjim** [comment]
## simple-search, input=slp1 works
The 'suggestion' box works:
![image](https://user-images.githubusercontent.com/6393033/195649666-2faafd81-f4e3-4070-9482-81397b3f3641.png)

The retrieval works:
![image](https://user-images.githubusercontent.com/6393033/195650334-afcaae6e-49bb-41a8-9c5b-5a77b06c18c8.png)

**Comment by funderburkjim** [comment]
## simple search, input='simple' 
This does not work:

![image](https://user-images.githubusercontent.com/6393033/195650785-fc0d3c05-f68a-4c6d-b72e-c5ddb96db7fe.png)

**Comment by funderburkjim** [comment]
## servepdf does not work
![image](https://user-images.githubusercontent.com/6393033/195651506-f99e6627-d4ad-4b4e-8c92-088fe183cf67.png)

I'll

**Comment by funderburkjim** [comment]
## the input=simple problem

The 'input=simple' problem is probably solved by 
regenerating hwnorm1c.sqlite. This binary file is
in csl-apidev/simple-search/hwnorm1/ 

It's regeneration is awkward, and not fully automated.

@drdhaval2785 I'll let you work through this in a separate issue.
Start by looking at csl-apidev/simple-search/readme.org,
section 'ngram and hwnorm1c'.  This in turn directs you to the 'hwnorm1' repository ....
Somewhere (probably in hwnorm1/sanhw1) 'lrv' will need to be added to list of dictionaries.

**Comment by gasyoun** [comment]
> Somewhere (probably in hwnorm1/sanhw1) 'lrv' will need to be added to list of dictionaries.

Yeah, @drdhaval2785 wants to go through it all ))

**Comment by drdhaval2785** [comment]
sanhw1.txt and hwnorm1c.txt and hwnorm1c.sqlite have been updated.
Maybe @funderburkjim may give it a try and install it in Cologne server to see if it works.

**Comment by funderburkjim** [comment]
## lrv-simple now ok
Have installed csl-apidev repository at cologne.
Tried simple-search on LRV.  Looks fine to me:

![image](https://user-images.githubusercontent.com/6393033/197919368-639c40ae-35e4-47fd-b027-8844fe262869.png)

**Comment by drdhaval2785** [comment]
@funderburkjim Would you please add this LRV dictionary to CDS?

**Comment by funderburkjim** [comment]
## additional steps
 csl-homepage repository updated for LRV, pushed to github, pulled at cologne.
Similarly, csl-doc repository.

@drdhaval2785   I think this completes the installation of LRV. Will let you close issue.

**Comment by funderburkjim** [comment]
Added comment in [newsletter april2023.md](https://github.com/sanskrit-lexicon/csl-newsletter/blob/main/april2023.md) for lrv.

Found (from the april2022.md file) reference to https://github.com/hrishikeshrt/PyCDSL.  Looks like a major project.  
@drdhaval2785  Are you working with Hrishikesh Terdalkar? Will he need to update something based on new LRV dictionary?

**Comment by drdhaval2785** [comment]
I will intimate Hrishikesh about addition of new dictionaries. He may have to update the documentation about dictionary codes.

**Comment by drdhaval2785** [comment]
I checked with the old version of pyCDSL installed in my computer. He will not have to do anything. The program is structured to download data based on CDSL dictionary codes themselves.

I typed 
‘cdsl -d LRV -s kamala’

The LRV data was downloaded from web folder of Cologne and results were displayed.

**Comment by drdhaval2785** [comment]
@funderburkjim 
PyCDSL is a good tool for two reasons.
1. It helps nerds who do not want to come out of their terminals for finding dictionary meanings.
2. It provides good python wrapper around dictionary data. Coders can use that for developing new python applications using Cologne data.

**Comment by funderburkjim** [comment]
pyCDSL is assuming some CDSL API --  There should be an 'official' location for the details of this api.

This official location would be beneficial 
* so CDSL knows what downstream users depend on. 
  * so CDSL does not accidentally break parts of the API
  * so CDSL can enhance the API
* so downstream developers 
   * know the API features that they can rely  on
   * have a place where they can suggest API enhancements.

**Comment by gasyoun** [comment]
> This official location would be beneficial

Right, you have a clue where it should be located?

**Comment by funderburkjim** [comment]
> where should CDSL api documentation be located?

Probably a new repository sanskrit-lexicon/csl-api.  

I would say the current api conventions are of an informal nature.

A more formal (official) api would likely be modeled after the JSON-based approach used by Github.

The nearest first step towards a more formal api may be to construct the csl-api repository and
gather, in an issue (or issues), all the current parameterized urls of cdsl.
