### ISSUE TITLE
page sequence v/s page column

### ISSUE THREAD

**Issue by drdhaval2785** [sanskrit-lexicon/LRV#2]
@Andhrabharati has marked page-sequence in LRV.
The main purpose of page-column is to facilitate location of the entry inside the given page.
page-sequence would also serve similar purpose.
Therefore, currently keeping this page-sequence data inside `<pc>` tag.
For display program, we can only use the page component of it.

**Comment by gasyoun** [comment]
> has marked page-sequence in LRV.

Does he ever eat or sleep?

**Comment by drdhaval2785** [comment]
It is just a documentation of a quirk. Not requiring any action.
