### ISSUE TITLE
lrvheader

### ISSUE THREAD

**Issue by funderburkjim** [sanskrit-lexicon/LRV#22]
@drdhaval2785  
https://sanskrit-lexicon.uni-koeln.de/scans/LRVScan/2022/web/lrvheader.xml
Gives error:

![image](https://user-images.githubusercontent.com/6393033/198169863-ad75b00f-9b96-4239-a6d3-3f9cb8bebcf0.png)

**Comment by drdhaval2785** [comment]
@funderburkjim 

It seems that you may need to do a fresh pull of csl-orig and regenerate. This bug in XML was corrected on 23 October 2022 via https://github.com/sanskrit-lexicon/csl-orig/commit/d90200951e009fe95d500962abcebb64c5198642

**Comment by funderburkjim** [comment]
After regenerating LRV at Cologne, above bug goes away.
