### ISSUE TITLE
LRV headwords not marked as per CDSL style

### ISSUE THREAD

**Issue by Andhrabharati** [sanskrit-lexicon/LRV#25]
@drdhaval2785 

I just happened to look into the cdsl file of LRV now, though it got included in the CDSL project long ago (Oct 2022).

You had properly tagged all the devanagari strings as {#...#} in the body portion (meanings area); but left the headword portion in slp1 alone, without tagging them.

This renders them out of the scope of reach of the "output transliteration change" in the display.

Pl. change the same (by marking those also with {#...#} tagging), by squeezing-in some time from your other activities.

If you cannot spare your time for this, you may just put a word here so that Jim might do the same in place of you.

**Comment by Andhrabharati** [comment]
BTW, a string not related to LRV is seen in the header file--

`<extent>9.3 MB (for armh.xml dictionary at Cologne)</extent>`

which should also be appropriately modified for LRV.

**Comment by funderburkjim** [comment]
The two omissions rectified.

@Andhrabharati  @drdhaval2785   I think this issue can be closed now.

**Comment by Andhrabharati** [comment]
Thank you Jim, for attending to this piece of work.
