### ISSUE TITLE
Multiple headword as first part and single word as second part of compound

### ISSUE THREAD

**Issue by drdhaval2785** [sanskrit-lexicon/LRV#9]
```
08054		<b> -अनिल	<b> कदंब, कदंबक-अनिल	<+> कदंब, कदंबकानिल	#-m.	$--1. a fragrant breeze, ते चोन्मीलितमालतीसुरभयः प्रौढः कदंबानिलाः /K.Pr./i.; 2. spring.	88
08055		<b> -कोरकन्याय	<b> कदंब, कदंबक-कोरकन्याय	<+> कदंब, कदंबककोरकन्याय	#-m.	$--the maxim of the <i>Kadamba</i> bud. It is applied to denote simultaneous rise or action, कदंबकोरकन्यायादुत्पत्तिः कस्यचिन्मते /Bh.P./	137
08056		<b> -वायु	<b> कदंब, कदंबक-वायु	<+> कदंब, कदंबकवायु	#-m.	$--a fragrant breeze.	21

```
Here, the intended parsing is `kadaMbAnila` and `kadaMbakAnila`.
Not `kadaMba` and `kadaMbakAnila`, as shown above.

**Comment by Andhrabharati** [comment]
Good finding, @drdhaval2785 !

I seem to have just padded the `<p>` string (whether it is a single word or a group) to the `<b>` string 'as is', and then combined the hyphened-words as the composite word.

So, finally you're to do some parsing work now!!

**Comment by drdhaval2785** [comment]
September 22 to October 4 commits handled these differences.
If any new item is found, it would be tracked separately.
